-- ----------------------------
-- Table structure for `countries`
-- ----------------------------
DROP TABLE IF EXISTS `countries`;
CREATE TABLE `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name_fa` varchar(50) NOT NULL,
  `name_en` varchar(50) NOT NULL,
  `tld` varchar(5) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=189 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of countries
-- ----------------------------
INSERT INTO `countries` VALUES ('2', 'آذربایجان', 'Azerbaijan', '');
INSERT INTO `countries` VALUES ('3', 'آفریقای جنوبی', 'South Africa', '');
INSERT INTO `countries` VALUES ('4', 'آفریقای مرکزی', 'Central African Republic', '');
INSERT INTO `countries` VALUES ('5', 'آلمان', 'Germany', '');
INSERT INTO `countries` VALUES ('6', 'آنتیگوا و باربودا', 'Antigua and Barbuda', '');
INSERT INTO `countries` VALUES ('7', 'آندورا', 'Andorra', '');
INSERT INTO `countries` VALUES ('8', 'آنگولا', 'Angola', '');
INSERT INTO `countries` VALUES ('9', 'اتریش', 'Austria', '');
INSERT INTO `countries` VALUES ('10', 'اتیوپی', 'Ethiopia', '');
INSERT INTO `countries` VALUES ('11', 'اردن', 'Jordan', '');
INSERT INTO `countries` VALUES ('12', 'ارمنستان', 'Armenia', '');
INSERT INTO `countries` VALUES ('13', 'اریتره', 'Eritrea', '');
INSERT INTO `countries` VALUES ('14', 'ازبکستان', 'Uzbekistan', '');
INSERT INTO `countries` VALUES ('15', 'اسپانیا', 'Spain', '');
INSERT INTO `countries` VALUES ('16', 'استرالیا', 'Australia', '');
INSERT INTO `countries` VALUES ('17', 'استونی', 'Estonia', '');
INSERT INTO `countries` VALUES ('18', 'اسلوواکی', 'Slovakia', '');
INSERT INTO `countries` VALUES ('19', 'اسلوونی', 'Slovenia', '');
INSERT INTO `countries` VALUES ('20', 'افغانستان', 'Afghanistan', '');
INSERT INTO `countries` VALUES ('21', 'الجزایر', 'Algeria', '');
INSERT INTO `countries` VALUES ('22', 'السالوادور', 'El Salvador', '');
INSERT INTO `countries` VALUES ('23', 'امارات متحده عربی', 'United Arab Emirates', '');
INSERT INTO `countries` VALUES ('24', 'امریکا', 'United States', '');
INSERT INTO `countries` VALUES ('25', 'اندونزی', 'Indonesia', '');
INSERT INTO `countries` VALUES ('26', 'اوروگوئه', 'Uruguay', '');
INSERT INTO `countries` VALUES ('27', 'اوگاندا', 'Uganda', '');
INSERT INTO `countries` VALUES ('28', 'اوکراین', 'Ukraine', '');
INSERT INTO `countries` VALUES ('29', 'اکووادور', 'Ecuador', '');
INSERT INTO `countries` VALUES ('30', 'ایتالیا', 'Italy', '');
INSERT INTO `countries` VALUES ('31', 'ایران', 'Iran', '');
INSERT INTO `countries` VALUES ('32', 'ایرلند', 'Ireland', '');
INSERT INTO `countries` VALUES ('33', 'ایسلند', 'Iceland', '');
INSERT INTO `countries` VALUES ('34', 'باربادوس', 'Barbados', '');
INSERT INTO `countries` VALUES ('35', 'باهاما', 'Bahamas', '');
INSERT INTO `countries` VALUES ('36', 'بحرین', 'Bahrain', '');
INSERT INTO `countries` VALUES ('37', 'برزیل', 'Brazil', '');
INSERT INTO `countries` VALUES ('38', 'برونئی', 'Brunei', '');
INSERT INTO `countries` VALUES ('39', 'بریتانیا', 'United Kingdom', '');
INSERT INTO `countries` VALUES ('40', 'بلاروس', 'Belarus', '');
INSERT INTO `countries` VALUES ('41', 'بلژیک', 'Belgium', '');
INSERT INTO `countries` VALUES ('42', 'بلغارستان', 'Bulgaria', '');
INSERT INTO `countries` VALUES ('43', 'بلیز', 'Belize', '');
INSERT INTO `countries` VALUES ('44', 'بنگلادش', 'Bangladesh', '');
INSERT INTO `countries` VALUES ('45', 'بنین', 'Benin', '');
INSERT INTO `countries` VALUES ('46', 'بوتان', 'Bhutan', '');
INSERT INTO `countries` VALUES ('47', 'بوتسوانا', 'Botswana', '');
INSERT INTO `countries` VALUES ('48', 'بوروندی', 'Burundi', '');
INSERT INTO `countries` VALUES ('49', 'بورکینافاسو', 'Burkina Faso', '');
INSERT INTO `countries` VALUES ('50', 'بولیوی', 'Bolivia', '');
INSERT INTO `countries` VALUES ('51', 'پاپواگینه نو', 'Papua New Guinea', '');
INSERT INTO `countries` VALUES ('52', 'پاراگوئه', 'Paraguay', '');
INSERT INTO `countries` VALUES ('53', 'پاناما', 'Panama', '');
INSERT INTO `countries` VALUES ('54', 'پاکستان', 'Pakistan', '');
INSERT INTO `countries` VALUES ('55', 'پرتغال', 'Portugal', '');
INSERT INTO `countries` VALUES ('56', 'پرو', 'Peru', '');
INSERT INTO `countries` VALUES ('57', 'تاجیکستان', 'Tajikistan', '');
INSERT INTO `countries` VALUES ('58', 'تانزانیا', 'Tanzania', '');
INSERT INTO `countries` VALUES ('59', 'تایلند', 'Thailand', '');
INSERT INTO `countries` VALUES ('60', 'ترکمنستان', 'Turkmenistan', '');
INSERT INTO `countries` VALUES ('61', 'ترکیه', 'Turkey', '');
INSERT INTO `countries` VALUES ('62', 'ترینیداد و توباگو', 'Trinidad and Tobago', '');
INSERT INTO `countries` VALUES ('63', 'توگو', 'Togo', '');
INSERT INTO `countries` VALUES ('64', 'تونس', 'Tunisia', '');
INSERT INTO `countries` VALUES ('65', 'تونگا', 'Tonga', '');
INSERT INTO `countries` VALUES ('66', 'تووالو', 'Tuvalu', '');
INSERT INTO `countries` VALUES ('67', 'چین تایپه-تایوان', 'Taiwan', '');
INSERT INTO `countries` VALUES ('68', 'آرژانتین', 'Argentina', '');
INSERT INTO `countries` VALUES ('69', 'آلبانی', 'Albania', '');
INSERT INTO `countries` VALUES ('70', 'جامائیکا', 'Jamaica', '');
INSERT INTO `countries` VALUES ('71', 'جزایر سلیمان', 'Solomon Islands', '');
INSERT INTO `countries` VALUES ('72', 'جیبوتی', 'Djibouti', '');
INSERT INTO `countries` VALUES ('73', 'مارشال', 'Marshall Islands', '');
INSERT INTO `countries` VALUES ('74', 'جمهوری چک', 'Czech Republic', '');
INSERT INTO `countries` VALUES ('75', 'چاد', 'Chad', '');
INSERT INTO `countries` VALUES ('76', 'چین', 'China', '');
INSERT INTO `countries` VALUES ('77', 'دانمارک', 'Denmark', '');
INSERT INTO `countries` VALUES ('78', 'دومنکن', 'Dominican', '');
INSERT INTO `countries` VALUES ('79', 'دومنیکا', 'Dominica', '');
INSERT INTO `countries` VALUES ('80', 'روآندا', 'Rwanda', '');
INSERT INTO `countries` VALUES ('81', 'روسیه', 'Russia', '');
INSERT INTO `countries` VALUES ('82', 'رومانی', 'Romania', '');
INSERT INTO `countries` VALUES ('83', 'زئیر-جمهوری کنگو', 'Congo', '');
INSERT INTO `countries` VALUES ('84', 'زامبیا', 'Zambia', '');
INSERT INTO `countries` VALUES ('85', 'زلاندنو', 'New Zealand', '');
INSERT INTO `countries` VALUES ('86', 'زيمباوه', 'Zimbabwe', '');
INSERT INTO `countries` VALUES ('87', 'ژاپن', 'Japan', '');
INSERT INTO `countries` VALUES ('88', 'سائوتومه و پرنسیپ', 'SAO TOME AND PRINCIPE', '');
INSERT INTO `countries` VALUES ('89', 'ساحل عاج-کوت دیوار', 'COTE D''IVOIRE', '');
INSERT INTO `countries` VALUES ('90', 'ساموای غربی', 'Samoa', '');
INSERT INTO `countries` VALUES ('91', 'سان مارینو', 'San Marino', '');
INSERT INTO `countries` VALUES ('92', 'سریلانکا', 'Sri Lanka', '');
INSERT INTO `countries` VALUES ('93', 'سشیل', 'Seychelles', '');
INSERT INTO `countries` VALUES ('94', 'سنت لوسیا', 'Saint Lucia', '');
INSERT INTO `countries` VALUES ('95', 'سنت وینست و گرنادین', 'Saint Vincent and the Grenadines', '');
INSERT INTO `countries` VALUES ('96', 'سنت کیتس و نویس', 'Saint Kitts and Nevis', '');
INSERT INTO `countries` VALUES ('97', 'سنگاپور', 'Singapore', '');
INSERT INTO `countries` VALUES ('98', 'سنگال', 'Senegal', '');
INSERT INTO `countries` VALUES ('99', 'سوئد', 'Sweden', '');
INSERT INTO `countries` VALUES ('100', 'سوئیس', 'Switzerland', '');
INSERT INTO `countries` VALUES ('101', 'سوازیلند', 'Swaziland', '');
INSERT INTO `countries` VALUES ('102', 'سودان', 'Sudan', '');
INSERT INTO `countries` VALUES ('103', 'سورینام', 'Suriname', '');
INSERT INTO `countries` VALUES ('104', 'سوریه', 'Syria', '');
INSERT INTO `countries` VALUES ('105', 'سومالی', 'Somalia', '');
INSERT INTO `countries` VALUES ('106', 'سیرالئون', 'Sierra Leone', '');
INSERT INTO `countries` VALUES ('107', 'شیلی', 'Chile', '');
INSERT INTO `countries` VALUES ('108', 'عراق', 'Iraq', '');
INSERT INTO `countries` VALUES ('109', 'عربستان', 'Saudi Arabia', '');
INSERT INTO `countries` VALUES ('110', 'عمان', 'Oman', '');
INSERT INTO `countries` VALUES ('111', 'غنا', 'Ghana', '');
INSERT INTO `countries` VALUES ('112', 'فرانسه', 'France', '');
INSERT INTO `countries` VALUES ('113', 'فنلاند', 'Finland', '');
INSERT INTO `countries` VALUES ('114', 'فیجی', 'Fiji', '');
INSERT INTO `countries` VALUES ('115', 'فیلیپین', 'Philippines', '');
INSERT INTO `countries` VALUES ('116', 'قبرس', 'Cyprus', '');
INSERT INTO `countries` VALUES ('117', 'قرقیزستان', 'Kyrgyzstan', '');
INSERT INTO `countries` VALUES ('118', 'قزاقستان', 'Kazakhstan', '');
INSERT INTO `countries` VALUES ('119', 'قطر', 'Qatar', '');
INSERT INTO `countries` VALUES ('120', 'کاستاریکا', 'Costa Rica', '');
INSERT INTO `countries` VALUES ('121', 'کامبوج', 'Cambodia', '');
INSERT INTO `countries` VALUES ('122', 'کامرون', 'Cameroon', '');
INSERT INTO `countries` VALUES ('123', 'کانادا', 'Canada', '');
INSERT INTO `countries` VALUES ('124', 'کرواسی', 'Croatia', '');
INSERT INTO `countries` VALUES ('125', 'کرۀ جنوبی', 'Korea, South', '');
INSERT INTO `countries` VALUES ('126', 'کرۀ شمالی', 'Korea, North', '');
INSERT INTO `countries` VALUES ('127', 'کلمبیا', 'Colombia', '');
INSERT INTO `countries` VALUES ('128', 'کنیا', 'Kenya', '');
INSERT INTO `countries` VALUES ('129', 'کوبا', 'Cuba', '');
INSERT INTO `countries` VALUES ('130', 'کویت', 'Kuwait', '');
INSERT INTO `countries` VALUES ('131', 'کیپ ورد', 'Cape Verde', '');
INSERT INTO `countries` VALUES ('132', 'کیریباس', 'Kiribati', '');
INSERT INTO `countries` VALUES ('133', 'گابون', 'Gabon', '');
INSERT INTO `countries` VALUES ('134', 'گامبیا', 'Gambia', '');
INSERT INTO `countries` VALUES ('135', 'گراندا', 'Grenada', '');
INSERT INTO `countries` VALUES ('136', 'گرجستان', 'Georgia', '');
INSERT INTO `countries` VALUES ('137', 'گواتمالا', 'Guatemala', '');
INSERT INTO `countries` VALUES ('138', 'گویان', 'Guyana', '');
INSERT INTO `countries` VALUES ('139', 'گینه', 'Guinea', '');
INSERT INTO `countries` VALUES ('140', 'گینۀ استوائی', 'Equatorial Guinea', '');
INSERT INTO `countries` VALUES ('141', 'گینۀ بیسائو', 'Guinea-Bissau', '');
INSERT INTO `countries` VALUES ('142', 'لائوس', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', '');
INSERT INTO `countries` VALUES ('143', 'لاتوی', 'Latvia', '');
INSERT INTO `countries` VALUES ('144', 'لبنان', 'Lebanon', '');
INSERT INTO `countries` VALUES ('145', 'لسوتو', 'Lesotho', '');
INSERT INTO `countries` VALUES ('146', 'لهستان', 'Poland', '');
INSERT INTO `countries` VALUES ('147', 'لوکزامبورک', 'Luxembourg', '');
INSERT INTO `countries` VALUES ('148', 'لیبریا', 'Liberia', '');
INSERT INTO `countries` VALUES ('149', 'لیبی', 'Libya', '');
INSERT INTO `countries` VALUES ('150', 'لیتوانی', 'Lithuania', '');
INSERT INTO `countries` VALUES ('151', 'لیختن اشتاین', 'Liechtenstein', '');
INSERT INTO `countries` VALUES ('152', 'ماداگاسکار', 'Madagascar', '');
INSERT INTO `countries` VALUES ('153', 'مالاوی', 'Malawi', '');
INSERT INTO `countries` VALUES ('154', 'مالت', 'Malta', '');
INSERT INTO `countries` VALUES ('155', 'مالدیو', 'Maldives', '');
INSERT INTO `countries` VALUES ('156', 'مالزی', 'Malaysia', '');
INSERT INTO `countries` VALUES ('157', 'مالی', 'Mali', '');
INSERT INTO `countries` VALUES ('158', 'مجارستان', 'Hungary', '');
INSERT INTO `countries` VALUES ('159', 'مصر', 'Egypt', '');
INSERT INTO `countries` VALUES ('160', 'مغرب- مراکش', 'Morocco', '');
INSERT INTO `countries` VALUES ('161', 'مغولستان', 'Mongolia', '');
INSERT INTO `countries` VALUES ('162', 'مقدونیه', 'Macedonia', '');
INSERT INTO `countries` VALUES ('163', 'موریتانی', 'Mauritania', '');
INSERT INTO `countries` VALUES ('164', 'موریس', 'Mauritius', '');
INSERT INTO `countries` VALUES ('165', 'موزامبیک', 'Mozambique', '');
INSERT INTO `countries` VALUES ('166', 'مولدووا', 'Moldova', '');
INSERT INTO `countries` VALUES ('167', 'موناکو', 'Monaco', '');
INSERT INTO `countries` VALUES ('168', 'مکزیک', 'Mexico', '');
INSERT INTO `countries` VALUES ('169', 'میانمار(برمه)', 'Myanmar', '');
INSERT INTO `countries` VALUES ('170', 'میکرونوزی', 'Micronesia', '');
INSERT INTO `countries` VALUES ('171', 'نائورو', 'Nauru', '');
INSERT INTO `countries` VALUES ('172', 'نامبیا', 'Namibia', '');
INSERT INTO `countries` VALUES ('173', 'نپال', 'Nepal', '');
INSERT INTO `countries` VALUES ('174', 'نروژ', 'Norway', '');
INSERT INTO `countries` VALUES ('175', 'نیجر', 'Niger', '');
INSERT INTO `countries` VALUES ('176', 'نیجریه', 'Nigeria', '');
INSERT INTO `countries` VALUES ('177', 'نیکاراگوئه', 'Nicaragua', '');
INSERT INTO `countries` VALUES ('178', 'واتیکان', 'Vatican City', '');
INSERT INTO `countries` VALUES ('179', 'وانواتو', 'Vanuatu', '');
INSERT INTO `countries` VALUES ('180', 'ونزوئلا', 'Venezuela', '');
INSERT INTO `countries` VALUES ('181', 'ویتنام', 'VIET NAM', '');
INSERT INTO `countries` VALUES ('182', 'هائیتی', 'Haiti', '');
INSERT INTO `countries` VALUES ('183', 'هلند', 'Netherlands', '');
INSERT INTO `countries` VALUES ('184', 'هندوراس', 'Honduras', '');
INSERT INTO `countries` VALUES ('185', 'هندوستان', 'India', '');
INSERT INTO `countries` VALUES ('186', 'صربستان و مونته نگرو', 'Montenegro', '');
INSERT INTO `countries` VALUES ('187', 'یمن', 'Yemen', '');
INSERT INTO `countries` VALUES ('188', 'یونان', 'Greece', '');
